export const ADD_MOVIE_AS_UNWATCH = 'ADD_MOVIE_AS_UNWATCH';
export const ADD_MOVIE_AS_WATCH = 'ADD_MOVIE_AS_WATCH';
export const REMOVE_MOVIE_FROM_WATCH = 'REMOVE_MOVIE_FROM_WATCH';
export const SEARCH_MY_MOVIE = 'SEARCH_MY_MOVIE';
export const SEARCH_MOVIE_ACTION = 'SEARCH_MOVIE_ACTION';
export const SEARCH_MOVIE_ACTION_SUCCESS = `${SEARCH_MOVIE_ACTION}_SUCCESS`;
export const SEARCH_MOVIE_ACTION_FAILURE = `${SEARCH_MOVIE_ACTION}_FAILURE`;

